services:
  - type: web
    name: certificate-generator
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: PHP_VERSION  
        value: 8.1
    plan: starter